name: Publish to Test.PyPI.org

on:
  push:
    branches:
      - main

jobs:
  publish:
    environment:
      name: Development
    name: Publish distribution 📦 to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Installing python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing git
        run: pip install gitpython

      - name: Installing Packages
        run: pip install -r requirements.txt

      - name: Generating version file
        run: python freeze_version.py

      - name: Setup python wheel
        run: pip install wheel

      - name: Building Package
        run: python setup.py bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkMjI4MzZiZmItNTE0OC00YzllLTg3OTgtMGJiNjY1ODBjM2JmAAIqWzMsImM2ZTYyNmQ1LWMyNTMtNGMxZi05YWEyLTFiZmQ4OWU2YjliOCJdAAAGIAZlUHE1PVK8jXQKT-znOghKQzmUfzwOPEDcGQBVig_Q
          repository_url: https://test.pypi.org/legacy/